# Default
defaultContentLanguage = "en"
sectionPagesMenu = "main"

[params]
noindex = false

[params.About]
title = "caodoc"
author = "caodoc"
description = "\"You&#39;re a wanderer, just like me.\""
source = "https://github.com/caodoc"
baseURL = "https://caodoc.is-a.dev"
imageURL = "https://raw.githubusercontent.com/caodoc/caodoc.github.io/main/assets/preview.png"

[params.Theme]
themeColor = "#000000"
palette = "mocha"

# Head Menu
[menu]
    [[menu.main]]
        identifier = "notes"
        name = "notes"
        url = "/n/"
        weight = 10

    [[menu.main]]
        identifier = "repo"
        name = "repo"
        url = "/r/"
        weight = 20

    [[menu.main]]
        identifier = "stuff"
        name = "stuff"
        url = "/s/"
        weight = 30